[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stride-imu"
version = "0.1"
requires-python = ">=3.10,<3.13"
dependencies = [
    "numpy==1.26.4",
    "scipy==1.11.4",
    "pandas==2.2.2",
    "matplotlib==3.8.4",
    "h5py==3.10.0",
    "openpyxl>=3.1.5",
]

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "ipympl>=0.10.0",
    "jupyterlab>=4.6.3",
    "nbconvert>=7.17.1",
    "nbformat>=5.11.1",
]
